### ISSUE TITLE
Add instructions to README for locally building the site

### ISSUE THREAD

**Issue by cthoyt** [earth-metabolome-initiative/earth-metabolome-initiative.legacy-website#4]
The email said we should feel free to update our own pages, but I don't have any way of checking that this update looks correct or not since I don't know anything about the underlying technology (I guess it's netlify?) that's running the site. please add some docs so I can build the site locally, ideally with docker so I don't have to install some specialized tool chain

**Comment by oolonek** [comment]
Hi @cthoyt you are right.
I added some instructions on the README. Let me know if OK or not ?

The website uses [Wowchemy](https://wowchemy.com/) templates. It is deployed not by netlify but by Github Pages, following https://www.jameswright.xyz/post/20200409/deploy_wowchemy_to_githubio/ and https://mickaellalande.github.io/post/tutorial/how-to-create-an-academic-github-page-with-hugo/

It does require to have hugo installed. I am not that confortable with establishing a docker. If you think it worth it (instead of the hugo install) happy to look at this with you.

**Comment by cthoyt** [comment]
Figuring out how to install Hugo wasn't a fun process - it took 5 clicks on their website to find it. I'd also rather not install yet another programming language on my system.

It appears there's a docker image at https://hub.docker.com/r/klakegg/hugo with instructions on how to run it, so you only need to copy/paste the instructions on how to run it via docker to avoid this potential frustration

**Comment by oolonek** [comment]
Right, added the docker command to the README

**Comment by cthoyt** [comment]
> Right, added the docker command to the README

Uh I'm sorry but this wasn't what I had in mind - the more links you make someone follow, the more frustrated they're going to get (I'm the one getting frustrated here, and so will everyone one of the other dozens of people who are listed on this page).

Can you please figured out exactly what the command you need to paste into the shell and make sure that is explicitly in the readme, with text like "paste these commands exactly into the terminal"

Normally I would follow-up on this myself and send a PR but I am thin on time at the moment

**Comment by oolonek** [comment]
Correct (I didn't run the docker command since I had it localy, and indeed was not the good command). Thanks for pressing here.

Let me know if the instructions added in 40b5b47cf97 look OK ?
